### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by callmemarcleo** [RobinMuehBFH/EWEB-portfolio#1]
There is a tiny typo in your about-me component (html)

[typo](https://github.com/RobinMuehBFH/EWEB-portfolio/blob/31118131a673721158b998bb2c7789decaddbd95/frontend/portfolio/src/app/components/about-me/about-me.component.html#L47)

**Comment by timotheeMM** [comment]
@RobinMuehBFH, @callmemarcleo 
You can close this issue.
It has been solved.

**Comment by RobinMuehBFH** [comment]
@timotheeMM 
ty for the reminder.
